"""POSIX shell (bash/zsh/sh) activation script."""

from __future__ import annotations

from .base import Activator

BASH_ACTIVATE = """\
# This file must be used with "source __VENV_BIN_NAME_SLASH__/activate" *from bash*
# you cannot run it directly
# generated by tn-venv

deactivate () {
    # reset old environment variables
    if [ -n "${_OLD_VIRTUAL_PATH:-}" ] ; then
        PATH="${_OLD_VIRTUAL_PATH:-}"
        export PATH
        unset _OLD_VIRTUAL_PATH
    fi
    if [ -n "${_OLD_VIRTUAL_PYTHONHOME:-}" ] ; then
        PYTHONHOME="${_OLD_VIRTUAL_PYTHONHOME:-}"
        export PYTHONHOME
        unset _OLD_VIRTUAL_PYTHONHOME
    fi

    # forget past commands
    hash -r 2> /dev/null

    if [ -n "${_OLD_VIRTUAL_PS1:-}" ] ; then
        PS1="${_OLD_VIRTUAL_PS1:-}"
        export PS1
        unset _OLD_VIRTUAL_PS1
    fi

    unset VIRTUAL_ENV
    unset VIRTUAL_ENV_PROMPT
    if [ ! "${1:-}" = "nondestructive" ] ; then
    # Self destruct!
        unset -f deactivate
    fi
}

# unset irrelevant variables
deactivate nondestructive

VIRTUAL_ENV=__VENV_DIR_SH__
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH=__VENV_BIN_PATH_SH__":$PATH"
export PATH

# unset PYTHONHOME if set
if [ -n "${PYTHONHOME:-}" ] ; then
    _OLD_VIRTUAL_PYTHONHOME="${PYTHONHOME:-}"
    unset PYTHONHOME
fi

if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1:-}"
    PS1="(__VENV_PROMPT__) ${PS1:-}"
    export PS1
    VIRTUAL_ENV_PROMPT="(__VENV_PROMPT__) "
    export VIRTUAL_ENV_PROMPT
fi

# Make sure to unalias pydoc if it's already there
alias pydoc 2> /dev/null >/dev/null && unalias pydoc || true

pydoc () {
    python -m pydoc "$@"
}

hash -r 2> /dev/null
"""


class BashActivator(Activator):
    name = "bash"
    templates = {"activate": BASH_ACTIVATE}
    executable_names = ("activate",)
