"""csh / tcsh activation script."""

from __future__ import annotations

from .base import Activator

CSH_ACTIVATE = """\
# This file must be used with "source __VENV_BIN_NAME_SLASH__/activate.csh" *from csh*.
# You cannot run it directly.
# generated by tn-venv

alias deactivate 'test $?_OLD_VIRTUAL_PATH != 0 && setenv PATH "$_OLD_VIRTUAL_PATH:q" && unset _OLD_VIRTUAL_PATH; rehash; test $?_OLD_VIRTUAL_PROMPT != 0 && set prompt="$_OLD_VIRTUAL_PROMPT:q" && unset _OLD_VIRTUAL_PROMPT; unsetenv VIRTUAL_ENV; unsetenv VIRTUAL_ENV_PROMPT; test "\\!:*" != "nondestructive" && unalias deactivate && unalias pydoc'

# Unset irrelevant variables.
deactivate nondestructive

setenv VIRTUAL_ENV "__VENV_DIR__"

set _OLD_VIRTUAL_PATH="$PATH:q"
setenv PATH "$VIRTUAL_ENV:q/__VENV_BIN_NAME_SLASH__:$PATH:q"



if ("__VENV_PROMPT__" != "") then
    set env_name = "__VENV_PROMPT__"
else
    set env_name = '__VENV_NAME__'
endif

if ( $?VIRTUAL_ENV_DISABLE_PROMPT ) then
    if ( $VIRTUAL_ENV_DISABLE_PROMPT == "" ) then
        set do_prompt = "1"
    else
        set do_prompt = "0"
    endif
else
    set do_prompt = "1"
endif

if ( $do_prompt == "1" ) then
    # Could be in a non-interactive environment,
    # in which case, $prompt is undefined and we wouldn't
    # care about the prompt anyway.
    if ( $?prompt ) then
        set _OLD_VIRTUAL_PROMPT="$prompt:q"
        if ( "$prompt:q" =~ *"$newline:q"* ) then
            :
        else
            set prompt = "(" "$env_name:q" ") $prompt:q"
        endif
    endif
endif

unset do_prompt

setenv VIRTUAL_ENV_PROMPT "($env_name:q) "
unset env_name

alias pydoc python -m pydoc

rehash
"""


class CShActivator(Activator):
    name = "csh"
    templates = {"activate.csh": CSH_ACTIVATE}
    executable_names = ("activate.csh",)
