"""Nushell activation script."""

from __future__ import annotations

from .base import Activator

NU_ACTIVATE = """\
# virtualenv activation module (generated by tn-venv)
# Activate with `overlay use activate.nu`
# Deactivate with `deactivate`, as usual

export-env {
    def has-env [name: string] {
        (get env -o | columns | where $it == $name | length) > 0
    }

    let is_windows = ($nu.os-info.name | str downcase) == "windows"
    let virtual_env = r#'__VENV_DIR__'#
    let bin = r#'__VENV_BIN_NAME_SLASH__'#
    let path_sep = (char esep)
    let venv_path = ([$virtual_env $bin] | path join)

    let old_path = ($env.PATH | if (has-env "PATH") { $in } else { $env.Path })
    let old_path = if ($old_path | describe) == "string" {
        $old_path | split row (char esep)
    } else {
        $old_path
    }

    let new_path = ([$venv_path] | append $old_path)

    let old_prompt = (if (has-env "VIRTUAL_ENV_PROMPT_OLD") { $env.VIRTUAL_ENV_PROMPT_OLD } else { "" })

    $env.VIRTUAL_ENV = $virtual_env
    $env.VIRTUAL_ENV_PROMPT = "__VENV_PROMPT__"
    $env.PATH = $new_path

    # If there is no default prompt, then only the env is printed in the prompt
    $env.PROMPT_COMMAND = {||
        let virtual_prompt = (if ("__VENV_PROMPT__" == "") { "" } else { $"(__VENV_PROMPT__) " })
        $virtual_prompt
    }
}
"""


class NushellActivator(Activator):
    name = "nushell"
    templates = {"activate.nu": NU_ACTIVATE}
    executable_names = ("activate.nu",)
