"""PowerShell activation script (Activate.ps1)."""

from __future__ import annotations

from .base import Activator

PS_ACTIVATE = r"""
<#
.Synopsis
Activate a Python virtual environment (generated by tn-venv).
#>

function global:deactivate ([switch]$NonDestructive) {
    # Revert to original values
    if (Test-Path variable:_OLD_VIRTUAL_PATH) {
        $env:PATH = $variable:_OLD_VIRTUAL_PATH
        Remove-Variable "_OLD_VIRTUAL_PATH" -Scope global
    }

    if (Test-Path function:_old_virtual_prompt) {
        $function:prompt = $function:_old_virtual_prompt
        Remove-Item function:\_old_virtual_prompt
    }

    if ($env:VIRTUAL_ENV) {
        Remove-Item env:VIRTUAL_ENV -ErrorAction SilentlyContinue
    }

    if ($env:VIRTUAL_ENV_PROMPT) {
        Remove-Item env:VIRTUAL_ENV_PROMPT -ErrorAction SilentlyContinue
    }

    if (!$NonDestructive) {
        # Self destruct!
        Remove-Item function:deactivate
    }
}

deactivate -nondestructive

$env:VIRTUAL_ENV = __VENV_DIR_PS__

$script:_OLD_VIRTUAL_PATH = $env:PATH
$env:PATH = "$env:VIRTUAL_ENV/__VENV_BIN_NAME_SLASH__" + [System.IO.Path]::PathSeparator + $env:PATH

# unset PYTHONHOME if set
if ($env:PYTHONHOME) {
    $script:_OLD_VIRTUAL_PYTHONHOME = $env:PYTHONHOME
    Remove-Item env:PYTHONHOME
}

if (-not $env:VIRTUAL_ENV_DISABLE_PROMPT) {
    function global:_old_virtual_prompt {
        ""
    }
    $function:_old_virtual_prompt = $function:prompt

    function global:prompt {
        # Add the virtualenv prefix to the current prompt.
        Write-Host -NoNewline -ForegroundColor Green "(__VENV_PROMPT__) "
        _old_virtual_prompt
    }
    $env:VIRTUAL_ENV_PROMPT = __VENV_PROMPT_PS__
}

# Clear PYTHONHOME restore state not needed when activation starts
if (Test-Path variable:_OLD_VIRTUAL_PYTHONHOME) {
    Remove-Variable _OLD_VIRTUAL_PYTHONHOME -Scope script -ErrorAction SilentlyContinue
}
"""


class PowerShellActivator(Activator):
    name = "powershell"
    templates = {"Activate.ps1": PS_ACTIVATE}
