"""activate_this.py — activate an environment from inside a running Python.

Legacy-compatible with virtualenv's ``activate_this.py``: users ``exec()``
the file (commonly via ``exec(open(...).read(), {'__file__': ...})``) to
rewrite ``sys.path`` and ``os.environ`` of the current process.
"""

from __future__ import annotations

from .base import Activator

PY_ACTIVATE_THIS = '''\
"""Activate this virtual environment inside the *current* Python process.

Usage::

    activate_this = "__VENV_BIN_NAME_SLASH__/activate_this.py"
    with open(activate_this) as f:
        code = compile(f.read(), activate_this, "exec")
        exec(code, {"__file__": activate_this})

Generated by tn-venv.
"""

import os
import site
import sys

bin_abs_path = os.path.dirname(os.path.abspath(__file__))
base = os.path.dirname(bin_abs_path)

# prepend bin to PATH (this file is inside the bin directory)
os.environ["PATH"] = os.pathsep.join(
    [bin_abs_path] + os.environ.get("PATH", "").split(os.pathsep)
)
os.environ["VIRTUAL_ENV"] = base  # virtual env is right above bin directory
os.environ["VIRTUAL_ENV_PROMPT"] = "__VENV_PROMPT__"

# add the virtual environments libraries to the host python import mechanism
prev_length = len(sys.path)
for lib in ("__VENV_LIB_REL__",):
    path = os.path.realpath(os.path.join(base, lib))
    site.addsitedir(path)
sys.path[:] = sys.path[prev_length:] + sys.path[0:prev_length]
sys.real_prefix = sys.prefix  # type: ignore[attr-defined]
sys.prefix = base
'''


class PythonActivator(Activator):
    name = "python"
    templates = {"activate_this.py": PY_ACTIVATE_THIS}

    def replacements(self, ctx):
        repl = super().replacements(ctx)
        lib_rel = ctx.lib_path.relative_to(ctx.env_dir).as_posix()
        repl["__VENV_LIB_REL__"] = lib_rel
        return repl
