name: Mypy Type Check
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install mypy
        run: pip install mypy

      - name: Create venv
        run: |
          pip install tn-venv
          tn-venv

      - name: Run Pyrefly Check
        run: |
          source .venv/bin/activate
          mypy .
